### ISSUE TITLE
Consider exporting to asciidoc

### ISSUE THREAD

**Issue by jni** [elegant-scipy/elegant-scipy#175]
@amueller has written an AsciiDoc exporter, which might be a better build artefact for O'Reilly than plain HTML.

**Comment by jni** [comment]
Oops, link:

https://github.com/jupyter/nbconvert/pull/355

**Comment by amueller** [comment]
They need to write the Atlas config but then you can probably work with
their build system from the start.
The main pain points are internal references (though I have a kinda hacky
solution) and figures, which are tricky because pandoc doesn't really have
a concept of captions. One possibility would be to embed the figure names
and captions in the raw nbconvert json.
I highly recommend working with asciidoc from the start.

**Comment by stefanv** [comment]
The jupyter asciidoc exporter did not work for our book (it's got a lot of crazy markup).  Could debug, but for now we'll go the Markdown -> HTMLBook route.

**Comment by amueller** [comment]
hm what markup didn't work? That's odd.. were you using html?

**Comment by stefanv** [comment]
It generated boldface for each IPython prompt entry, e.g., which is illegal asciidoc.
