### ISSUE TITLE
Problems with build dependencies 

### ISSUE THREAD

**Issue by m-bob** [elegant-scipy/elegant-scipy#338]
First, I think the instruction in _Build_ an isolated environment called "elegant-scipy" and install the necessary dependencies_:

conda env create --name elegant-scipy -f path/to/environment.yml

makes no sense.

I think the line should look like:

conda env create --name elegant-scipy -f path/to/download-elegant-scipy-directory/requirements.txt

(That is both the directory part of the path and the file part of the path are incorrect.)

Second, that command still does not work for me. I get

13:17:24 ~ 507 >  conda env create --name elegant-scipy -f /Users/me/Downloads/elegant-scipy/requirements.txt
Using Anaconda Cloud api site https://api.anaconda.org
Solving environment: failed

ResolvePackageNotFound:
  - bs4
  - jupytercontrib[version='>=0.0.5']
  - notedown[version='>=1.4']

Can you help?

Thanks!

**Comment by jni** [comment]
Hi @m-bob and thanks for your interest in our book!

Actually, the first part of your point is right, it would be clearer to point to the elegant-scipy. But the second part, it turns out, was already correct. Conda is a different dependency management from pip, and it needs a file called environment.yml, which we've provided. So it should be:

```
conda env create --name elegant-scipy -f /path/to/elegant-scipy/environment.yml
```

And that should work!

I'll update the README with your suggestion. Don't hesitate to write again if you have any more issues!

**Comment by m-bob** [comment]
Dear Juan,

Thank you! Thank you! I ran 'make all' and everything  looks like it worked
properly.

Also, thanks for being so gracious. I didn't see the file 'environment.yml'
in the downloaded directory and I kept interpreting
'/path/to/environment.yml' (which is what you wrote and which is correct)
as '/path/to/environment' as a directory followed by a filename of '.yml' .
It's my bad.

(I ordered your book today, after I entered the "issue" and before hearing
 back. I'm looking forwafd to reading and using it.)

Again, thank you for a fast, generous and courteous reply.

Yours,

Murray
